<?php
namespace Test\Query\Select;
use steph\db_query\Entity\User;
use steph\db_query\Query;

class QueryTest extends \PHPUnit\Framework\TestCase{
    /**
     * @var Query
     */
    private $query;

    protected function setUp(): void
{
    $config = [
        'host'=> 'localhost',
        'name'=>'dbquerytest',
        'user'=>'stephane',
        'password'=>'password'
    ];
    $this->query = new Query($config);
    parent::setUp(); // TODO: Change the autogenerated stub
}

public function testSelectAllQueries(){
    try {
        /** @var User[] $result */
        $result = $this->query->select()->from('user')->run_fetch(true)->getResult();
        print_r($result);
        $this->assertInstanceOf(User::class,$result[0]);
        $this->assertEquals('steph',$result[0]->getUsername());
    } catch (\steph\db_query\Exception\StephQBUILDEREXCEPTION $e) {
        print($e);
    } catch (Exception $e) {
        print($e);
    }
}
}